/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "secondary-container": "#474746",
        "secondary": "#e5e2e1",
        "tertiary": "#ffe798",
        "on-tertiary-fixed-variant": "#675400",
        "surface-container-low": "#131313",
        "inverse-on-surface": "#565554",
        "tertiary-fixed": "#fdd73e",
        "surface-container-high": "#201f1f",
        "primary": "#f6ffc0",
        "surface": "#0e0e0e",
        "on-primary-container": "#505d00",
        "inverse-primary": "#586500",
        "error-dim": "#d53d18",
        "error": "#ff7351",
        "on-primary-fixed-variant": "#596700",
        "secondary-fixed": "#e5e2e1",
        "on-tertiary": "#665300",
        "surface-container-lowest": "#000000",
        "on-primary": "#586500",
        "error-container": "#b92902",
        "secondary-dim": "#d6d4d3",
        "on-primary-fixed": "#3f4900",
        "tertiary-fixed-dim": "#eec930",
        "surface-container-highest": "#262626",
        "on-tertiary-fixed": "#463900",
        "on-surface": "#ffffff",
        "on-secondary-fixed": "#403f3f",
        "primary-fixed": "#daf900",
        "outline": "#777575",
        "surface-variant": "#262626",
        "on-surface-variant": "#adaaaa",
        "on-secondary": "#525151",
        "surface-container": "#1a1919",
        "primary-fixed-dim": "#cdea00",
        "primary-dim": "#d0ed00",
        "on-error": "#450900",
        "tertiary-dim": "#eec930",
        "surface-tint": "#f6ffc0",
        "tertiary-container": "#fdd73e",
        "on-tertiary-container": "#5c4b00",
        "on-error-container": "#ffd2c8",
        "background": "#0e0e0e",
        "on-secondary-container": "#d2d0cf",
        "primary-container": "#daf900",
        "inverse-surface": "#fcf8f8",
        "surface-bright": "#2c2c2c",
        "secondary-fixed-dim": "#d6d4d3",
        "on-secondary-fixed-variant": "#5c5b5b",
        "surface-dim": "#0e0e0e",
        "on-background": "#ffffff",
        "outline-variant": "#494847",
        "neutral-900": "#171717",
        "neutral-950": "#0a0a0a",
        "neutral-800": "#262626",
        "neutral-500": "#737373",
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Manrope", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
